version: '3.8'
volumes:
  postgres-data:

networks:
  secondhandhaven:
    driver: bridge

services:
  fronted:
    build:
      context: ../second-hand-haven-frontend
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    networks:
      - secondhandhaven
    ports:
      - 3000:80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    networks:
      - secondhandhaven
    ports:
      - ${PORT}:8080
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    ports:
      - 4000:${POSTGRES_PORT}
    networks:
      - secondhandhaven
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

