

export enum PriceOfferEvent {
    CREATE = 'PRODUCT_OFFER_CREATE',
    UPDATE = 'PRODUCT_OFFER_UPDATE',
    SUCCESS_CREATE = 'PRODUCT_OFFER_SUCCESS_CREATE',
    SUCCESS_UPDATE = 'PRODUCT_OFFER_SUCCESS_UPDATE',
}
