
export enum NotificationEvent {
    GET_NOTIFICATION_BY_ID = 'GET_NOTIFICATION_BY_ID',
    GET_NOTIFICATION_BY_ID_SUCCESS = 'GET_NOTIFICATION_BY_ID_SUCCESS',
    DELETE_NOTIFICATION_BY_ID = 'DELETE_NOTIFICATION_BY_ID',
    DELETE_NOTIFICATION_BY_ID_SUCCESS = 'DELETE_NOTIFICATION_BY_ID_SUCCESS',
    POST_NOTIFICATION_SUCCESS = 'POST_NOTIFICATION_SUCCESS',
    READ_NOTIFICATION = 'READ_NOTIFICATION',
    READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS',
}
