import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1707054089333 implements MigrationInterface {
    name = 'Initial1707054089333'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "local_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "password" character varying(250), CONSTRAINT "PK_8cccb06418fc19839799cca7ca2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "google_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "social_id" character varying(250) NOT NULL, CONSTRAINT "PK_9cc4d01b0d5174b0fa8b38d22e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facebook_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "social_id" character varying(250) NOT NULL, CONSTRAINT "PK_2cc28e32030154b60c5f1bfb1d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."auth_provider_enum" AS ENUM('LOCAL', 'GOOGLE', 'FACEBOOK')`);
        await queryRunner.query(`CREATE TABLE "auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "email" character varying(250) NOT NULL, "refresh_token" character varying, "reset_password_token" character varying, "is_according_term_use" boolean NOT NULL DEFAULT true, "provider" "public"."auth_provider_enum" NOT NULL DEFAULT 'LOCAL', "localAuthId" uuid, "facebookAuthId" uuid, "googleAuthId" uuid, CONSTRAINT "UQ_b54f616411ef3824f6a5c06ea46" UNIQUE ("email"), CONSTRAINT "REL_275172a727a75d17a00c5afd12" UNIQUE ("localAuthId"), CONSTRAINT "REL_93fa12c1ce05c881f9bdc150e5" UNIQUE ("facebookAuthId"), CONSTRAINT "REL_bfa6ac53df86bf577abd528433" UNIQUE ("googleAuthId"), CONSTRAINT "PK_7e416cf6172bc5aec04244f6459" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "value" character varying, "attribute_id" uuid, "product_id" uuid, CONSTRAINT "PK_f9b91f38df3dbbe481d9e056e5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "default_attribute_value" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "value" character varying NOT NULL, "attributeId" uuid, CONSTRAINT "PK_20911e1f234f70e55f7b9f40dac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attribute_type_enum" AS ENUM('NUMBER_INPUT', 'SINGLE_SELECTOR', 'MULTI_SELECTOR', 'INPUT', 'CHECKBOX')`);
        await queryRunner.query(`CREATE TABLE "attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying(200) NOT NULL, "type" "public"."attribute_type_enum" NOT NULL DEFAULT 'SINGLE_SELECTOR', "is_sortable" boolean NOT NULL DEFAULT false, "is_filterable" boolean NOT NULL DEFAULT false, "is_required" boolean NOT NULL DEFAULT false, "meta" jsonb, CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "category_id" uuid, "attribute_id" uuid, CONSTRAINT "PK_e71950e2873d76c1fdb37b75b1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "order" integer NOT NULL DEFAULT '0', "parentId" uuid, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid, CONSTRAINT "REL_512bf776587ad5fc4f804277d7" UNIQUE ("user_id"), CONSTRAINT "PK_620bff4a240d66c357b5d820eaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_wishlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "wishlist_id" uuid, "product_id" uuid, CONSTRAINT "PK_d6bcf44bc941aad244e9e817dea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid, CONSTRAINT "REL_f091e86a234693a49084b4c2c8" UNIQUE ("user_id"), CONSTRAINT "PK_c524ec48751b9b5bcfbf6e59be7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_cart" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL DEFAULT '1', "cart_id" uuid, "product_id" uuid, CONSTRAINT "PK_a9eb3c6b183961debec3a968f91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "image" character varying, "product_id" uuid, CONSTRAINT "PK_99d98a80f57857d51b5f63c8240" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_reader" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "message_id" uuid, "reader_id" uuid, CONSTRAINT "PK_d17435b1187bcf060abef023a1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_chat_role_enum" AS ENUM('BUYER', 'SELLER')`);
        await queryRunner.query(`CREATE TABLE "user_chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "role" "public"."user_chat_role_enum" NOT NULL DEFAULT 'BUYER', "user_id" uuid, "chat_id" uuid, CONSTRAINT "PK_c43d9c7669f5c12f23686e1b891" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."price_offer_status_enum" AS ENUM('EXPECTED', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "price_offer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "price" numeric NOT NULL DEFAULT '0', "status" "public"."price_offer_status_enum" NOT NULL DEFAULT 'EXPECTED', "product_id" uuid, "user_id" uuid, CONSTRAINT "PK_2d9f387f7531a172f0ffb13c8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_type_enum" AS ENUM('PLAIN_TEXT', 'EXPECTED_OFFER', 'APPROVED_OFFER', 'REJECTED_OFFER')`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "text" character varying(500) NOT NULL, "entity_id" uuid, "type" "public"."message_type_enum" NOT NULL DEFAULT 'PLAIN_TEXT', "chat_id" uuid, "user_chat_id" uuid, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "product_id" uuid, CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('CREATED', 'CANCEL', 'EXPECT_PAYMENT', 'NOT_PAYED', 'CONFIRMED', 'DELIVERING', 'RETURNED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "status" "public"."order_status_enum" NOT NULL DEFAULT 'CREATED', "receiver_first_name" character varying(100) NOT NULL, "receiver_last_name" character varying(100) NOT NULL, "phone_number" character varying(10) NOT NULL, "address_line" character varying(200) NOT NULL, "city" character varying(500) NOT NULL, "zip_code" character varying(10) NOT NULL, "track_id" character varying(50), "buyer_id" uuid, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "price" numeric NOT NULL, "product_id" uuid, "order_id" uuid, CONSTRAINT "PK_539ede39e518562dfdadfddb492" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "price" numeric NOT NULL, "description" character varying(5000), "count_view" numeric NOT NULL DEFAULT '0', "reserved_price" numeric, "is_sold" boolean NOT NULL DEFAULT false, "owner_id" uuid, "category_id" uuid, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "address_line1" character varying(1000) NOT NULL, "city" character varying(500) NOT NULL, "zip_code" character varying(10) NOT NULL, "user_id" uuid, CONSTRAINT "REL_ef1357621134458dc6aa0c4b92" UNIQUE ("user_id"), CONSTRAINT "PK_f81527a1b48d655ce69b6962a0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_account_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "account_number" character varying(32) NOT NULL DEFAULT '', "social_security_number" character varying(32) NOT NULL DEFAULT '', "user_id" uuid, CONSTRAINT "REL_af5d951e848dd9b11cbe11b331" UNIQUE ("user_id"), CONSTRAINT "PK_7d57672b4576c595d2e4c0ec2b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_recipient" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_read" boolean NOT NULL, "notification_id" uuid, "recipient_id" uuid, CONSTRAINT "PK_9830357f52360a126737d498e66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('EXPECT_OFFER')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "type" "public"."notification_type_enum" NOT NULL DEFAULT 'EXPECT_OFFER', "entity_id" uuid NOT NULL, "sender_id" uuid, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_system_role_enum" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "first_name" character varying(100) NOT NULL, "last_name" character varying(100), "image_url" character varying, "is_email_subscribe" boolean NOT NULL DEFAULT false, "is_email_confirm" boolean NOT NULL DEFAULT false, "system_role" "public"."user_system_role_enum" NOT NULL DEFAULT 'USER', "public_profile_id" character varying(200) NOT NULL, "phone_number" character varying(14) NOT NULL DEFAULT '', "about_me" character varying(510) NOT NULL DEFAULT '', "authId" uuid, CONSTRAINT "UQ_01eea41349b6c9275aec646eee0" UNIQUE ("phone_number"), CONSTRAINT "REL_ad5065ee18a722baaa932d1c3c" UNIQUE ("authId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "fee" numeric NOT NULL DEFAULT '0', "aur_fee" numeric NOT NULL DEFAULT '0', "admin_email" character varying NOT NULL DEFAULT '', CONSTRAINT "PK_52a90627e2f00c0b5aa3ef60bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_8da8666fc72217687e9b4f4c7e9" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4aa1348fc4b7da9bef0fae8ff4" ON "category_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a22002acac4976977b1efd114" ON "category_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_275172a727a75d17a00c5afd126" FOREIGN KEY ("localAuthId") REFERENCES "local_auth"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_93fa12c1ce05c881f9bdc150e52" FOREIGN KEY ("facebookAuthId") REFERENCES "facebook_auth"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_bfa6ac53df86bf577abd5284339" FOREIGN KEY ("googleAuthId") REFERENCES "google_auth"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_3e2f6a0f059b619505f30b8e54f" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_c8f119684d209b55cf5e8b42532" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "default_attribute_value" ADD CONSTRAINT "FK_0b6eaa2ccaf9009a2557ef981a9" FOREIGN KEY ("attributeId") REFERENCES "attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attribute" ADD CONSTRAINT "FK_e8145c8dfcb858b614ba1d73014" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attribute" ADD CONSTRAINT "FK_0b0fc4dc2cc0e32c47d7b71f1a3" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_d5456fd7e4c4866fec8ada1fa10" FOREIGN KEY ("parentId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist" ADD CONSTRAINT "FK_512bf776587ad5fc4f804277d76" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_wishlist" ADD CONSTRAINT "FK_89dc0a67d7b388f1d79aa3d7635" FOREIGN KEY ("wishlist_id") REFERENCES "wishlist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_wishlist" ADD CONSTRAINT "FK_49b9f34ac2e43a9972123090c36" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_f091e86a234693a49084b4c2c86" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cart" ADD CONSTRAINT "FK_cac311a56f904d99846892a9da3" FOREIGN KEY ("cart_id") REFERENCES "cart"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_cart" ADD CONSTRAINT "FK_7e1ab60d5bc931ef26a1b825d14" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reader" ADD CONSTRAINT "FK_8d378c48524e621b0958d51c57a" FOREIGN KEY ("message_id") REFERENCES "message"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reader" ADD CONSTRAINT "FK_7c3bf779d431cf5972e1efeadf7" FOREIGN KEY ("reader_id") REFERENCES "user_chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_7633fe1395d0705b301a21cf4d3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_5366da78c4f08914a33f6e23d51" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offer" ADD CONSTRAINT "FK_f5809eb247fc9853535d4064ce4" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offer" ADD CONSTRAINT "FK_058463f56fd90b716ff57e7c9ca" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_859ffc7f95098efb4d84d50c632" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_5e9f7546bd1f484474cb3f27b71" FOREIGN KEY ("user_chat_id") REFERENCES "user_chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_559df52fbbd8924a051b0e4680b" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_8724877ec30a3aab629727b36ed" FOREIGN KEY ("buyer_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_400f1584bf37c21172da3b15e2d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_ea143999ecfa6a152f2202895e2" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_c2eedda8bf0194e1fb299ee7424" FOREIGN KEY ("owner_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_info" ADD CONSTRAINT "FK_ef1357621134458dc6aa0c4b926" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" ADD CONSTRAINT "FK_f6ebcb1bb7f7f55e33cf8488065" FOREIGN KEY ("notification_id") REFERENCES "notification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" ADD CONSTRAINT "FK_493f58abfb2de28c393b9e2cbe2" FOREIGN KEY ("recipient_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_56023c91b76b36125acd4dcd9c5" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ad5065ee18a722baaa932d1c3c6" FOREIGN KEY ("authId") REFERENCES "auth"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_closure" ADD CONSTRAINT "FK_4aa1348fc4b7da9bef0fae8ff48" FOREIGN KEY ("id_ancestor") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_closure" ADD CONSTRAINT "FK_6a22002acac4976977b1efd114a" FOREIGN KEY ("id_descendant") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "category_closure" DROP CONSTRAINT "FK_6a22002acac4976977b1efd114a"`);
        await queryRunner.query(`ALTER TABLE "category_closure" DROP CONSTRAINT "FK_4aa1348fc4b7da9bef0fae8ff48"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ad5065ee18a722baaa932d1c3c6"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_56023c91b76b36125acd4dcd9c5"`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" DROP CONSTRAINT "FK_493f58abfb2de28c393b9e2cbe2"`);
        await queryRunner.query(`ALTER TABLE "notification_recipient" DROP CONSTRAINT "FK_f6ebcb1bb7f7f55e33cf8488065"`);
        await queryRunner.query(`ALTER TABLE "shipping_info" DROP CONSTRAINT "FK_ef1357621134458dc6aa0c4b926"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_c2eedda8bf0194e1fb299ee7424"`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_ea143999ecfa6a152f2202895e2"`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_400f1584bf37c21172da3b15e2d"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_8724877ec30a3aab629727b36ed"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_559df52fbbd8924a051b0e4680b"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_5e9f7546bd1f484474cb3f27b71"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_859ffc7f95098efb4d84d50c632"`);
        await queryRunner.query(`ALTER TABLE "price_offer" DROP CONSTRAINT "FK_058463f56fd90b716ff57e7c9ca"`);
        await queryRunner.query(`ALTER TABLE "price_offer" DROP CONSTRAINT "FK_f5809eb247fc9853535d4064ce4"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_5366da78c4f08914a33f6e23d51"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_7633fe1395d0705b301a21cf4d3"`);
        await queryRunner.query(`ALTER TABLE "message_reader" DROP CONSTRAINT "FK_7c3bf779d431cf5972e1efeadf7"`);
        await queryRunner.query(`ALTER TABLE "message_reader" DROP CONSTRAINT "FK_8d378c48524e621b0958d51c57a"`);
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3"`);
        await queryRunner.query(`ALTER TABLE "product_cart" DROP CONSTRAINT "FK_7e1ab60d5bc931ef26a1b825d14"`);
        await queryRunner.query(`ALTER TABLE "product_cart" DROP CONSTRAINT "FK_cac311a56f904d99846892a9da3"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_f091e86a234693a49084b4c2c86"`);
        await queryRunner.query(`ALTER TABLE "product_wishlist" DROP CONSTRAINT "FK_49b9f34ac2e43a9972123090c36"`);
        await queryRunner.query(`ALTER TABLE "product_wishlist" DROP CONSTRAINT "FK_89dc0a67d7b388f1d79aa3d7635"`);
        await queryRunner.query(`ALTER TABLE "wishlist" DROP CONSTRAINT "FK_512bf776587ad5fc4f804277d76"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_d5456fd7e4c4866fec8ada1fa10"`);
        await queryRunner.query(`ALTER TABLE "category_attribute" DROP CONSTRAINT "FK_0b0fc4dc2cc0e32c47d7b71f1a3"`);
        await queryRunner.query(`ALTER TABLE "category_attribute" DROP CONSTRAINT "FK_e8145c8dfcb858b614ba1d73014"`);
        await queryRunner.query(`ALTER TABLE "default_attribute_value" DROP CONSTRAINT "FK_0b6eaa2ccaf9009a2557ef981a9"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_c8f119684d209b55cf5e8b42532"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_3e2f6a0f059b619505f30b8e54f"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_bfa6ac53df86bf577abd5284339"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_93fa12c1ce05c881f9bdc150e52"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_275172a727a75d17a00c5afd126"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a22002acac4976977b1efd114"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4aa1348fc4b7da9bef0fae8ff4"`);
        await queryRunner.query(`DROP TABLE "category_closure"`);
        await queryRunner.query(`DROP TABLE "payment_config"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_system_role_enum"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "notification_recipient"`);
        await queryRunner.query(`DROP TABLE "bank_account_info"`);
        await queryRunner.query(`DROP TABLE "shipping_info"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "order_product"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "chat"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TYPE "public"."message_type_enum"`);
        await queryRunner.query(`DROP TABLE "price_offer"`);
        await queryRunner.query(`DROP TYPE "public"."price_offer_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_chat"`);
        await queryRunner.query(`DROP TYPE "public"."user_chat_role_enum"`);
        await queryRunner.query(`DROP TABLE "message_reader"`);
        await queryRunner.query(`DROP TABLE "product_image"`);
        await queryRunner.query(`DROP TABLE "product_cart"`);
        await queryRunner.query(`DROP TABLE "cart"`);
        await queryRunner.query(`DROP TABLE "product_wishlist"`);
        await queryRunner.query(`DROP TABLE "wishlist"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "category_attribute"`);
        await queryRunner.query(`DROP TABLE "attribute"`);
        await queryRunner.query(`DROP TYPE "public"."attribute_type_enum"`);
        await queryRunner.query(`DROP TABLE "default_attribute_value"`);
        await queryRunner.query(`DROP TABLE "product_attribute"`);
        await queryRunner.query(`DROP TABLE "auth"`);
        await queryRunner.query(`DROP TYPE "public"."auth_provider_enum"`);
        await queryRunner.query(`DROP TABLE "facebook_auth"`);
        await queryRunner.query(`DROP TABLE "google_auth"`);
        await queryRunner.query(`DROP TABLE "local_auth"`);
    }

}
